import "./css/globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import Drawer from "./components/drawer";
import { AuthProvider } from "./Providers";

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Riperdoc",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={robotoMono.className}>
				<div className='wrapper'>
					<AuthProvider>
						{children}
						<Drawer />
					</AuthProvider>
				</div>
			</body>
		</html>
	);
}
